### PR TITLE
Run django unit tests

### PR DESCRIPTION
**Pull request by jvacek**
Weird that #49 didn't catch the failing test..?

### CODE REVIEW

**Comment by jvacek** [comment]
@fabiocaccamo You might want to vastly increase the matrix size, and also add a second column for django versions which you intend to support. As this will add up a _lot_ of github action minutes, you might want to make it run only on your own approval

**Comment by fabiocaccamo** [comment]
@jvacek yes, really weird, I think that add the django tests to the GitHub CI is a good idea.
You can find the matrix in both [tox.ini](https://github.com/fabiocaccamo/django-treenode/blob/master/tox.ini) and [.travis.yml](https://github.com/fabiocaccamo/django-treenode/blob/master/.travis.yml) files.

**Comment by jvacek** [comment]
Ah, then it might be worth looking into this maybe? Might be easier to maintain too https://github.com/ymyzk/tox-gh-actions

**Comment by fabiocaccamo** [comment]
I didn't know about `tox-gh-actions`, it would perfect!

**Comment by jvacek** [comment]
@fabiocaccamo I'm not at all familiar with `tox` and the way it runs tests, do you think you could check this out? https://github.com/fabiocaccamo/django-treenode/runs/4226223874?check_suite_focus=true

**Comment by jvacek** [comment]
@fabiocaccamo the unit tests are running correctly now, and have already flagged an issue about `force_text` being deprecated https://docs.djangoproject.com/en/3.2/ref/utils/#django.utils.encoding.force_text

**Comment by fabiocaccamo** [comment]
@jvacek the test suite didn't run because I finished the free credits on travis, now I replaced travis with GitHub action.

**Pull request closed without merging**
